version: '3.8'

services: 
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todonet

  backend:
    build:
      context: ./backend
    ports:
      - "8086:8086"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - todonet

  db:
    image: postgres:15
    container_name: postgres-todo
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
    networks:
      - todonet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todo_pgdata:

networks:
  todonet:
